### ISSUE TITLE
[REDACTED] 

### ISSUE THREAD

**Issue by CO-111** [ShaneFlandermeyer/mpar-sim#1]
I was trying to run the raster_scan example from your mpar-sim library, but I encountered an issue. When running the example, I received an error message stating "No module named 'mpar_sim.initiator'". It seems like there might be a missing module or file in the library.

Could you please provide some guidance on how to resolve this issue? Perhaps there are additional installation steps or dependencies required?

Thank you for your assistance.

**Comment by ShaneFlandermeyer** [comment]
At this point, I would only recommend using this repo as a code reference and not a library (the develop branch is probably best for this). Everything here is more or less exclusively tailored for stuff I did for my master's work, and I no longer actively maintain it. 

I've archived the repo to make this more clear.
